name: Release Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.3'

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release
      working-directory: ./ # Adjust if your Flutter project is in a subdirectory

    - name: Generate Tag
      id: generate_tag
      run: |
        # Generate a tag based on the number of commits
        TAG="v$(git rev-list --count HEAD)"
        echo "TAG=${TAG}" >> $GITHUB_ENV

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      with:
        tag_name: ${{ env.TAG }}
        release_name: Release ${{ env.TAG }}
        draft: false
        prerelease: false
        body: |
          ## Changelog
          ${{ github.event.head_commit.message }}

    - name: Upload Release APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/app/outputs/flutter/release/app-release.apk
        asset_name: app-release-${{ env.TAG }}.apk
        asset_content_type: application/vnd.android.package-archive
