name: Create GitHub Release

on:
  push:
    tags:
      - "master"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Build APK
        run: shorebird release android -- --release
      #   - name: Create GitHub Release
      #     uses: actions/create-release@v1
      #     with:
      #       tag_name: ${{ github.ref }}
      #       release_name: ${{ github.ref }}
      #       body: Release description
      #       draft: false
      #       prerelease: false
      #   - name: Upload APK
      #     uses: actions/upload-release-asset@v1
      #     with:
      #       upload_url: ${{ steps.create-release.outputs.upload_url }}
      #       asset_path: path/to/your/app.apk
      #       asset_name: app-release.apk
      #       asset_content_type: application/vnd.android.package-archive
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: Release description
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Handle Release Creation Failure
        if: steps.CreateGitHubRelease.outcome == 'failure'
        run: |
          echo "Failed to create GitHub release:"
          echo "${{ steps.CreateGitHubRelease.outputs.error }}"
